---
- hosts: all
  become: yes
  tasks:
  - name: I want to install git on ubuntu
    apt:
      name: git
      state: present
  - name: want to install tree on ubuntu nodes
    apt:
      name: tree
      state: present
  - name: install wget on ubuntu
    apt:
      name: wget
      state: present
