---
- hosts: 172.31.17.136
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: i want to copy my index file into ansible node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
  - name: i want to download remote or internet files
    get_url: 
      url: https://get.jenkins.io/war-stable/2.319.1/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes